package com.saga.commons.enums;

public enum SubEvents {

	USER_VALIDATION, ITEM_VALIDATION, MERCHANT_VALIDATION, DELIVERY_EVENT, MERCHANT_ORDER, MERCHANT_ITEM_VALIDATION,
	ORDER_EVENT, PAYMENT_EVENT
}
